/**
 * 种子命令数据 — 新用户按标签初始化命令库
 * 按 7 个标签分类，每个标签 35 条，共 245 条常用/基础命令
 */

export interface SeedCommand {
  title: string
  content: string
  tags: string[]
  is_public: false
}

export const SEED_COMMANDS: SeedCommand[] = [
  // ==================== SSH (35 条) ====================
  { title: 'SSH 免密登录',     content: 'ssh-copy-id user@host',                                   tags: ['ssh'], is_public: false },
  { title: 'SSH 密钥生成',     content: 'ssh-keygen -t ed25519 -C "your_email@example.com"',       tags: ['ssh'], is_public: false },
  { title: 'SSH 本地端口转发', content: 'ssh -L 8080:localhost:80 user@host',                       tags: ['ssh'], is_public: false },
  { title: 'SSH 远程端口转发', content: 'ssh -R 9090:localhost:3000 user@host',                    tags: ['ssh'], is_public: false },
  { title: 'SSH 动态转发(SOCKS)', content: 'ssh -D 1080 user@host',                                 tags: ['ssh'], is_public: false },
  { title: 'SSH Config 多主机', content: `Host myserver\n  HostName 192.168.1.100\n  User root\n  Port 22\n  IdentityFile ~/.ssh/id_ed25519`, tags: ['ssh'], is_public: false },
  { title: 'SCP 远程拷贝',     content: 'scp -r local_folder user@host:/remote/path',               tags: ['ssh'], is_public: false },
  { title: 'rsync 增量同步',  content: 'rsync -avz -e ssh ./local user@host:/remote',               tags: ['ssh'], is_public: false },
  { title: 'SSH Agent 添加密钥', content: 'eval "$(ssh-agent -s)" && ssh-add ~/.ssh/id_ed25519',    tags: ['ssh'], is_public: false },
  { title: 'SSH 保活配置',     content: `Host *\n  ServerAliveInterval 60\n  ServerAliveCountMax 5`, tags: ['ssh'], is_public: false },
  { title: 'SSH Jump Host 跳板', content: `Host target\n  HostName 10.0.1.100\n  ProxyJump bastion\nHost bastion\n  HostName bastion.example.com`, tags: ['ssh'], is_public: false },
  { title: 'SSH 禁用密码登录', content: `# /etc/ssh/sshd_config\nPasswordAuthentication no\nPubkeyAuthentication yes\n# 重启: systemctl restart sshd`, tags: ['ssh'], is_public: false },
  { title: 'SSH 限制登录用户', content: `# /etc/ssh/sshd_config\nAllowUsers alice bob\n# 或组: AllowGroups sshusers`, tags: ['ssh'], is_public: false },
  { title: 'SSH 修改默认端口', content: `# /etc/ssh/sshd_config\nPort 2222\n# 重启: systemctl restart sshd`, tags: ['ssh'], is_public: false },
  { title: 'SSH 关闭 DNS 反查', content: `# /etc/ssh/sshd_config\nUseDNS no\n# 加速登录`, tags: ['ssh'], is_public: false },
  { title: 'SSH 远程执行命令', content: "ssh user@host 'ls -la /var/log'",                          tags: ['ssh'], is_public: false },
  { title: 'SSH X11 图形转发', content: 'ssh -X user@host        # 运行 GUI 程序',                  tags: ['ssh'], is_public: false },
  { title: 'SSH 密钥指纹查看', content: 'ssh-keygen -lf ~/.ssh/id_ed25519.pub',                     tags: ['ssh'], is_public: false },
  { title: 'SSH 提取公钥',     content: 'ssh-keygen -y -f ~/.ssh/id_ed25519 > ~/.ssh/id_ed25519.pub', tags: ['ssh'], is_public: false },
  { title: 'SSH Known Hosts 管理', content: 'ssh-keygen -R hostname          # 删除旧指纹\nssh-keyscan -H host >> ~/.ssh/known_hosts  # 添加', tags: ['ssh'], is_public: false },
  { title: 'SSH 通过跳板 scp', content: 'scp -o ProxyJump=bastion file user@target:/path',          tags: ['ssh'], is_public: false },
  { title: 'SSH 查看当前连接数', content: 'ss | grep -c ssh         # 或 who | wc -l',               tags: ['ssh'], is_public: false },
  { title: 'SSH 断开僵死连接', content: '~.         # SSH escape 断开\n# Enter + ~ + . 三键',       tags: ['ssh'], is_public: false },
  { title: 'SSH 禁止 Root 登录', content: `# /etc/ssh/sshd_config\nPermitRootLogin no`,             tags: ['ssh'], is_public: false },
  { title: 'SSH 密钥密码修改', content: 'ssh-keygen -p -f ~/.ssh/id_ed25519',                        tags: ['ssh'], is_public: false },
  { title: 'SSH Multiplexing 复用连接', content: `Host *\n  ControlMaster auto\n  ControlPath ~/.ssh/sockets/%r@%h-%p\n  ControlPersist 600`, tags: ['ssh'], is_public: false },
  { title: 'SSH 空口令登录禁止', content: `# /etc/ssh/sshd_config\nPermitEmptyPasswords no`,        tags: ['ssh'], is_public: false },
  { title: 'SSH 会话超时',     content: `# /etc/ssh/sshd_config\nClientAliveInterval 300\nClientAliveCountMax 2`, tags: ['ssh'], is_public: false },
  { title: 'SSH 查看失败登录', content: 'grep "Failed password" /var/log/auth.log | tail -20',      tags: ['ssh'], is_public: false },
  { title: 'SSH AuthorizedKeys 配置', content: `# ~/.ssh/authorized_keys 可选前缀\nfrom="192.168.1.0/24",no-agent-forwarding ssh-ed25519 AAA...`, tags: ['ssh'], is_public: false },
  { title: 'SSH 日志级别调试', content: 'ssh -vvv user@host       # 最详细调试信息',                 tags: ['ssh'], is_public: false },
  { title: 'SSH Fail2ban 防暴力破解', content: `# /etc/fail2ban/jail.local\n[sshd]\nenabled = true\nmaxretry = 3\nbantime = 3600`, tags: ['ssh'], is_public: false },
  { title: 'SSH Banner 警告信息', content: `# /etc/ssh/sshd_config\nBanner /etc/issue.net`,         tags: ['ssh'], is_public: false },
  { title: 'SSH SFTP 限目录',  content: `# /etc/ssh/sshd_config\nMatch Group sftponly\n  ChrootDirectory /home/%u\n  ForceCommand internal-sftp`, tags: ['ssh'], is_public: false },
  { title: 'SSH 端口敲门(Port Knocking)', content: '# 先敲端口序列再开放 SSH\nknock host 7000 8000 9000 && ssh user@host', tags: ['ssh'], is_public: false },

  // ==================== Docker (35 条) ====================
  { title: 'Docker 运行容器',   content: 'docker run -d --name myapp -p 8080:80 -v $(pwd):/app myimage:latest', tags: ['docker'], is_public: false },
  { title: 'Docker 进入容器',   content: 'docker exec -it container_name /bin/bash',                  tags: ['docker'], is_public: false },
  { title: 'Docker 查看日志',   content: 'docker logs -f --tail 100 container_name',                 tags: ['docker'], is_public: false },
  { title: 'Docker 构建镜像',   content: 'docker build -t myapp:v1.0 .',                             tags: ['docker'], is_public: false },
  { title: 'Docker Compose 启动', content: 'docker compose up -d --build',                            tags: ['docker'], is_public: false },
  { title: 'Docker 清理所有资源', content: 'docker system prune -a --volumes',                        tags: ['docker'], is_public: false },
  { title: 'Docker 查看资源使用', content: 'docker stats --no-stream',                               tags: ['docker'], is_public: false },
  { title: 'Docker 镜像导出/导入', content: 'docker save -o myapp.tar myapp && docker load -i myapp.tar', tags: ['docker'], is_public: false },
  { title: 'Docker 网络创建',   content: 'docker network create --driver bridge mynet',               tags: ['docker'], is_public: false },
  { title: 'Docker Volume 管理', content: 'docker volume create mydata && docker run -v mydata:/data ...', tags: ['docker'], is_public: false },
  { title: 'Docker 查看容器详情', content: 'docker inspect container_name | jq .',                     tags: ['docker'], is_public: false },
  { title: 'Docker 限制 CPU/内存', content: 'docker run -d --cpus="1.5" --memory="512m" --memory-swap="1g" nginx', tags: ['docker'], is_public: false },
  { title: 'Docker 多阶段构建', content: `FROM golang:1.21 AS builder\nWORKDIR /app\nCOPY . .\nRUN go build -o server\nFROM alpine:3.19\nCOPY --from=builder /app/server .\nCMD ["./server"]`, tags: ['docker'], is_public: false },
  { title: 'Docker .dockerignore', content: 'node_modules\n.git\n.env\n*.log\n.DS_Store\ndist/',      tags: ['docker'], is_public: false },
  { title: 'Docker 健康检查',   content: `HEALTHCHECK --interval=30s --timeout=3s --retries=3 \\\n  CMD curl -f http://localhost:8080/health || exit 1`, tags: ['docker'], is_public: false },
  { title: 'Docker 重启策略',   content: 'docker run -d --restart=unless-stopped nginx\nalways/no/on-failure[:N]/unless-stopped', tags: ['docker'], is_public: false },
  { title: 'Docker 环境变量',   content: 'docker run -e NODE_ENV=production -e PORT=3000 myapp',      tags: ['docker'], is_public: false },
  { title: 'Docker 容器重命名', content: 'docker rename old_name new_name',                           tags: ['docker'], is_public: false },
  { title: 'Docker 暂停/恢复',  content: 'docker pause container && docker unpause container',         tags: ['docker'], is_public: false },
  { title: 'Docker 查看容器变更', content: 'docker diff container_name',                              tags: ['docker'], is_public: false },
  { title: 'Docker 提交为新镜像', content: 'docker commit container_name newimage:v2',                tags: ['docker'], is_public: false },
  { title: 'Docker Tag 打标签', content: 'docker tag myapp:v1.0 registry.example.com/myapp:v1.0',    tags: ['docker'], is_public: false },
  { title: 'Docker 推送私有仓库', content: 'docker login registry.example.com\ndocker push registry.example.com/myapp:v1.0', tags: ['docker'], is_public: false },
  { title: 'Docker 查看镜像历史', content: 'docker history myapp:v1.0',                               tags: ['docker'], is_public: false },
  { title: 'Docker 容器文件拷贝', content: 'docker cp ./file container:/path\ndocker cp container:/path ./local_file', tags: ['docker'], is_public: false },
  { title: 'Docker 端口映射',   content: 'docker run -p 80:80 -p 443:443 -p 127.0.0.1:3306:3306 mysql', tags: ['docker'], is_public: false },
  { title: 'Docker Compose 完整示例', content: `services:\n  web:\n    build: .\n    ports: ["8080:80"]\n    depends_on:\n      - db\n  db:\n    image: postgres:16\n    environment:\n      POSTGRES_PASSWORD: secret`, tags: ['docker'], is_public: false },
  { title: 'Docker Context 管理', content: 'docker context ls\ndocker context create remote --docker "host=ssh://user@host"', tags: ['docker'], is_public: false },
  { title: 'Docker Buildx 多平台', content: 'docker buildx create --use\ndocker buildx build --platform linux/amd64,linux/arm64 -t myapp .', tags: ['docker'], is_public: false },
  { title: 'Docker 清理悬空镜像', content: 'docker image prune -a --filter "until=24h"',               tags: ['docker'], is_public: false },
  { title: 'Docker Bridge 网络', content: 'docker network inspect bridge | jq \'.[0].Containers\'',    tags: ['docker'], is_public: false },
  { title: 'Docker rootless 模式', content: 'dockerd-rootless-setuptool.sh install\n# 以非 root 运行 Docker 守护进程', tags: ['docker'], is_public: false },
  { title: 'Docker 查看事件流', content: 'docker events --since 1h      # 实时查看所有 docker 事件',    tags: ['docker'], is_public: false },
  { title: 'Docker Swarm 初始化', content: 'docker swarm init --advertise-addr 192.168.1.10\ndocker stack deploy -c docker-compose.yml mystack', tags: ['docker'], is_public: false },
  { title: 'Docker 查看容器进程', content: 'docker top container_name',                               tags: ['docker'], is_public: false },

  // ==================== Linux (35 条) ====================
  { title: '查找大文件 (>100MB)', content: 'find . -type f -size +100M -exec ls -lh {} \\;',          tags: ['linux'], is_public: false },
  { title: '批量替换文本',      content: "grep -rl 'old_str' . | xargs sed -i 's/old_str/new_str/g'",  tags: ['linux'], is_public: false },
  { title: '查看端口占用',      content: 'lsof -i :8080          # 或 ss -tlnp | grep 8080',          tags: ['linux'], is_public: false },
  { title: '磁盘使用分析',      content: 'df -h && du -sh /* 2>/dev/null | sort -rh | head -10',      tags: ['linux'], is_public: false },
  { title: '进程树查看',        content: 'ps auxf --sort=-%mem | head -20',                           tags: ['linux'], is_public: false },
  { title: '压缩/解压 tar',     content: 'tar -czvf archive.tar.gz folder/    # 解压: tar -xzvf archive.tar.gz', tags: ['linux'], is_public: false },
  { title: 'systemd 服务管理',  content: 'systemctl status|start|stop|restart|enable|disable service_name', tags: ['linux'], is_public: false },
  { title: 'crontab 定时任务',  content: '# 编辑: crontab -e\n# 每天 3 点执行: 0 3 * * * /path/to/script.sh\n# 字段: 分 时 日 月 周', tags: ['linux'], is_public: false },
  { title: 'iptables 防火墙',   content: '# 开放端口\niptables -A INPUT -p tcp --dport 80 -j ACCEPT\n# 查看规则\niptables -L -n -v', tags: ['linux'], is_public: false },
  { title: 'strace 系统调用调试', content: 'strace -f -o trace.log -p <pid>',                          tags: ['linux'], is_public: false },
  { title: '查看系统信息',      content: 'uname -a\necho $SHELL\necho $XDG_SESSION_TYPE',                tags: ['linux'], is_public: false },
  { title: '内存使用情况',      content: 'free -h           # 总览\ncat /proc/meminfo  # 详细',          tags: ['linux'], is_public: false },
  { title: 'CPU 信息',          content: "lscpu\necho '线程数:' $(nproc)\ncat /proc/cpuinfo | grep 'model name' | head -1", tags: ['linux'], is_public: false },
  { title: '查看内核版本',      content: 'uname -r           # 内核版本\ncat /etc/os-release # 发行版信息', tags: ['linux'], is_public: false },
  { title: '用户管理',          content: 'useradd -m -s /bin/bash username     # 创建用户\nusermod -aG sudo username          # 加入 sudo 组', tags: ['linux'], is_public: false },
  { title: '权限管理 chmod/chown', content: 'chmod 755 script.sh               # rwxr-xr-x\nchown user:group file              # 改变归属\nchmod -R 644 ./docs/', tags: ['linux'], is_public: false },
  { title: '软链接/硬链接',     content: 'ln -s /path/to/target link_name      # 软链接\nln /path/to/target hard_link         # 硬链接', tags: ['linux'], is_public: false },
  { title: '管道和重定向',      content: 'cmd > file.txt     # 覆盖重定向\ncmd >> file.txt    # 追加\ncmd 2>&1           # 合并 stderr\ncmd | tee file.txt', tags: ['linux'], is_public: false },
  { title: 'grep 正则搜索',     content: "grep -rn 'pattern' ./src          # 递归搜索\ngrep -v 'exclude' file             # 反向匹配\ngrep -A2 -B2 pattern file          # 上下文", tags: ['linux'], is_public: false },
  { title: 'awk 文本处理',      content: "awk '{print $1,$3}' file          # 打印列\nawk -F',' '{sum+=$2} END{print sum}'  # 求和\nawk 'NR>1' file  # 跳过首行", tags: ['linux'], is_public: false },
  { title: 'sort/uniq 去重统计', content: 'sort file | uniq -c | sort -rn | head -10',                 tags: ['linux'], is_public: false },
  { title: 'xargs 批量操作',    content: "find . -name '*.log' | xargs rm -f\n# 含空格: find . -print0 | xargs -0 rm", tags: ['linux'], is_public: false },
  { title: 'nohup 后台运行',    content: 'nohup ./long_task.sh > output.log 2>&1 &\ndisown           # 即使 shell 关闭也继续', tags: ['linux'], is_public: false },
  { title: 'watch 重复执行',    content: 'watch -n 2 -d "ls -lh /var/log"    # 每 2 秒刷新，高亮差异', tags: ['linux'], is_public: false },
  { title: 'alias 命令别名',    content: "alias ll='ls -alF'\nalias gs='git status'\n# 永久: 写入 ~/.bashrc", tags: ['linux'], is_public: false },
  { title: 'history 历史命令',  content: 'history | tail -50\n!42              # 执行第 42 条\n!!               # 上一条\n!$               # 上一条的最后参数', tags: ['linux'], is_public: false },
  { title: 'mount 挂载管理',    content: 'mount /dev/sdb1 /mnt/data\numount /mnt/data\n# 查看: mount | column -t', tags: ['linux'], is_public: false },
  { title: 'journalctl 日志',   content: 'journalctl -u nginx -f              # 实时跟踪\njournalctl --since "1 hour ago" -u ssh\n# 空间: journalctl --disk-usage', tags: ['linux'], is_public: false },
  { title: '时区设置',          content: 'timedatectl list-timezones\ntimedatectl set-timezone Asia/Shanghai', tags: ['linux'], is_public: false },
  { title: 'locale 语言环境',   content: 'locale -a              # 列出可用\nexport LANG=en_US.UTF-8  # 设置\nlocalectl set-locale LANG=en_US.UTF-8', tags: ['linux'], is_public: false },
  { title: 'ulimit 资源限制',   content: 'ulimit -n 65535         # 最大文件描述符\nulimit -a               # 查看所有限制\n# 永久: /etc/security/limits.conf', tags: ['linux'], is_public: false },
  { title: 'top/htop 实时监控', content: 'top -u username   # 只看某用户\n# htop 彩色交互界面\n# 按 P=CPU M=内存 T=时间排序', tags: ['linux'], is_public: false },
  { title: '查看硬件信息',      content: 'lspci                    # PCI 设备\nlsusb                    # USB 设备\nlshw -short              # 所有硬件', tags: ['linux'], is_public: false },
  { title: 'sysctl 内核参数',   content: 'sysctl -a | grep net.ipv4\n# 临时: sysctl -w net.ipv4.ip_forward=1\n# 永久: /etc/sysctl.conf', tags: ['linux'], is_public: false },
  { title: '查看开机时间/负载', content: 'uptime                   # 运行时间 + 负载\ncat /proc/loadavg',       tags: ['linux'], is_public: false },

  // ==================== Git (35 条) ====================
  { title: 'Git 撤销 commit',    content: 'git reset --soft HEAD~1        # 保留修改\ngit reset --hard HEAD~1              # 丢弃修改', tags: ['git'], is_public: false },
  { title: 'Git stash 暂存',    content: 'git stash push -m "WIP"\ngit stash pop        # 恢复最近\ngit stash list       # 查看列表', tags: ['git'], is_public: false },
  { title: 'Git reflog 恢复',   content: 'git reflog                # 所有操作历史\ngit reset --hard <hash>   # 恢复', tags: ['git'], is_public: false },
  { title: 'Git rebase 整理提交', content: 'git rebase -i HEAD~4\n# pick/squash/fixup/drop\n# 冲突: git rebase --continue/--abort', tags: ['git'], is_public: false },
  { title: 'Git cherry-pick',   content: 'git cherry-pick <commit>\ngit cherry-pick A..B         # 范围摘取', tags: ['git'], is_public: false },
  { title: 'Git bisect 二分调试', content: 'git bisect start\ngit bisect bad HEAD\ngit bisect good v1.0\n# 完成后: git bisect reset', tags: ['git'], is_public: false },
  { title: 'Git blame 逐行溯源', content: 'git blame -L 10,30 filename\n# 忽略空格变更: git blame -w', tags: ['git'], is_public: false },
  { title: 'Git diff 对比',     content: 'git diff HEAD~3..HEAD\ngit diff --stat\ngit diff branchA..branchB\ngit diff --name-only', tags: ['git'], is_public: false },
  { title: 'Git 清理远程分支引用', content: 'git remote prune origin\ngit fetch -p                     # fetch 时自动清理', tags: ['git'], is_public: false },
  { title: 'Git submodule 管理', content: 'git submodule add <url> <path>\ngit submodule update --init --recursive', tags: ['git'], is_public: false },
  { title: 'Git 全局配置',      content: 'git config --global user.name "Your Name"\ngit config --global user.email "email@example.com"\ngit config --global init.defaultBranch main', tags: ['git'], is_public: false },
  { title: 'Git 全局忽略文件',  content: '# ~/.gitignore_global\nnode_modules\n.DS_Store\n*.log\n.env\n# 应用: git config --global core.excludesfile ~/.gitignore_global', tags: ['git'], is_public: false },
  { title: 'Git 美化日志',      content: 'git log --oneline --graph --all --decorate\ngit log --pretty=format:"%h %s" --graph', tags: ['git'], is_public: false },
  { title: 'Git Tag 版本标签',  content: 'git tag v1.0.0\ngit tag -a v1.0.0 -m "release"  # 附注标签\ngit push origin --tags', tags: ['git'], is_public: false },
  { title: 'Git Worktree 多工作区', content: 'git worktree add ../project-hotfix hotfix-branch\ngit worktree list\ngit worktree remove ../project-hotfix', tags: ['git'], is_public: false },
  { title: 'Git Restore 恢复文件', content: 'git restore filename\ngit restore --source HEAD~2 filename', tags: ['git'], is_public: false },
  { title: 'Git Switch 切换分支', content: 'git switch main\ngit switch -c new-feature       # 创建并切换', tags: ['git'], is_public: false },
  { title: 'Git Merge 合并策略', content: 'git merge feature-branch\ngit merge --squash feature-branch    # 压缩合并\ngit merge --abort                    # 放弃合并', tags: ['git'], is_public: false },
  { title: 'Git Rerere 冲突复用', content: 'git config --global rerere.enabled true\ngit rerere forget <path>         # 忘记某冲突解决', tags: ['git'], is_public: false },
  { title: 'Git Format-Patch 补丁', content: 'git format-patch -3 HEAD      # 生成最近 3 个补丁\ngit am *.patch                 # 应用补丁', tags: ['git'], is_public: false },
  { title: 'Git Clean 清理未跟踪', content: 'git clean -n                   # 预览\ngit clean -fd                  # 删除未跟踪文件+目录', tags: ['git'], is_public: false },
  { title: 'Git Show 查看提交', content: 'git show <commit>\ngit show HEAD~2:path/to/file        # 查看历史版本文件', tags: ['git'], is_public: false },
  { title: 'Git Shortlog 统计',  content: 'git shortlog -sn               # 按作者统计\ngit shortlog -sn --no-merges    # 排除合并', tags: ['git'], is_public: false },
  { title: 'Git Archive 打包',   content: 'git archive --format=tar.gz HEAD > project.tar.gz\ngit archive -o latest.zip HEAD', tags: ['git'], is_public: false },
  { title: 'Git Sparse Checkout', content: 'git sparse-checkout init --cone\ngit sparse-checkout set src/components', tags: ['git'], is_public: false },
  { title: 'Git LFS 大文件管理', content: 'git lfs track "*.psd" "*.zip"\ngit lfs ls-files\ngit lfs prune', tags: ['git'], is_public: false },
  { title: 'Git Hooks 钩子',     content: `# .git/hooks/pre-commit\n#!/bin/sh\nnpm run lint || exit 1\n# chmod +x pre-commit`, tags: ['git'], is_public: false },
  { title: 'Git 命令别名',      content: 'git config --global alias.co checkout\ngit config --global alias.br branch\ngit config --global alias.lg "log --oneline --graph"', tags: ['git'], is_public: false },
  { title: 'Git GC 垃圾回收',   content: 'git gc --aggressive\ngit reflog expire --expire=now --all && git gc --prune=now  # 彻底清理', tags: ['git'], is_public: false },
  { title: 'Git Fsck 检查仓库', content: 'git fsck --full                # 检查对象完整性\ngit fsck --lost-found           # 找回悬空对象', tags: ['git'], is_public: false },
  { title: 'Git Describe 描述',  content: 'git describe --tags            # v1.0.0-3-gabc123', tags: ['git'], is_public: false },
  { title: 'Git Range-Diff',     content: 'git range-diff origin/main..old origin/main..new\n# 比较两个版本范围的差异', tags: ['git'], is_public: false },
  { title: 'Git Merge-Base',     content: 'git merge-base branchA branchB\n# 找到两个分支的共同祖先', tags: ['git'], is_public: false },
  { title: 'Git 修改最近提交信息', content: 'git commit --amend -m "new message"\ngit commit --amend --no-edit    # 追加文件不改信息', tags: ['git'], is_public: false },
  { title: 'Git 查看远程仓库',  content: 'git remote -v\ngit remote show origin\ngit remote add upstream <url>', tags: ['git'], is_public: false },

  // ==================== Vim (35 条) ====================
  { title: 'Vim 基本操作速查',   content: 'i → 插入 | Esc → 正常 | :w → 保存 | :q → 退出 | :wq → 保存退出\nu → 撤销 | Ctrl+r → 重做 | dd → 删行 | yy → 复制行 | p → 粘贴', tags: ['vim'], is_public: false },
  { title: 'Vim 搜索替换',      content: '/pattern        # 搜索\nn/N             # 下一个/上一个\n:%s/old/new/g   # 全局替换\n:%s/old/new/gc  # 带确认替换', tags: ['vim'], is_public: false },
  { title: 'Vim 窗口分割',      content: ':sp filename    # 水平分割\n:vsp filename   # 垂直分割\nCtrl+w h/j/k/l  # 窗口切换\nCtrl+w q        # 关闭窗口', tags: ['vim'], is_public: false },
  { title: 'Vim 宏录制',        content: 'qa              # 开始录制宏到寄存器 a\n...操作...\nq               # 停止录制\n@a              # 执行宏\n10@a            # 执行 10 次', tags: ['vim'], is_public: false },
  { title: 'Vim 寄存器',        content: ':reg            # 查看所有寄存器\n"ayy            # 复制到寄存器 a\n"ap             # 粘贴寄存器 a\n"+y / "+p       # 系统剪贴板', tags: ['vim'], is_public: false },
  { title: 'Vim 批量缩进',      content: '>> / <<         # 行缩进\n3>>             # 3 行缩进\nV 选中后 >       # 可视模式缩进\n==              # 自动格式化当前行', tags: ['vim'], is_public: false },
  { title: 'Vim buffer 管理',   content: ':ls             # 列出所有 buffer\n:bnext / :bprev # 切换\n:bd             # 关闭 buffer\n:e filename     # 打开文件', tags: ['vim'], is_public: false },
  { title: 'Vim 快速跳转',      content: 'gg              # 文件首\nG               # 文件尾\n:42             # 到第 42 行\n%               # 匹配括号\nCtrl+o/i        # 前进/后退', tags: ['vim'], is_public: false },
  { title: 'Vim 文件浏览 Netrw', content: ':Explore        # 目录浏览\n:Sexplore       # 水平分屏浏览\ni               # 切换显示模式', tags: ['vim'], is_public: false },
  { title: 'Vim 快速注释',      content: 'Ctrl+v 选中 + I + # + Esc     # 多行注释\ngc + 动作 (需插件)',               tags: ['vim'], is_public: false },
  { title: 'Vim 文本对象',      content: 'ciw             # 修改当前词\ndi( / di"        # 删除括号/引号内\nci{             # 修改花括号内\nvat             # 选中整个标签', tags: ['vim'], is_public: false },
  { title: 'Vim 大小写转换',    content: 'gUw             # 单词转大写\nguG             # 到文件尾转小写\n~               # 切换单字符大小写', tags: ['vim'], is_public: false },
  { title: 'Vim 折叠 (Folding)', content: 'zc              # 关闭折叠\nzo              # 打开折叠\nzR              # 全部展开\nzM              # 全部折叠\nzf5j            # 创建折叠(5行)', tags: ['vim'], is_public: false },
  { title: 'Vim 拼写检查',      content: ':set spell     # 开启拼写检查\n]s 上一个错误 | [s 下一个错误\nzg 加入词典 | z= 建议替换', tags: ['vim'], is_public: false },
  { title: 'Vim 自动补全',      content: 'Ctrl+n / Ctrl+p # 单词补全\nCtrl+x Ctrl+f   # 文件路径补全\nCtrl+x Ctrl+o   # 语义补全', tags: ['vim'], is_public: false },
  { title: 'Vim 标记 (Marks)',   content: 'ma              # 设置标记 a\n`a               # 跳转到标记 a\na                # 到标记 a 的行首\n:marks          # 列出所有标记', tags: ['vim'], is_public: false },
  { title: 'Vim 自定义快捷键',  content: `" .vimrc 示例:\nnnoremap <leader>w :w<CR>\nnnoremap <C-h> <C-w>h\nlet mapleader = " "`, tags: ['vim'], is_public: false },
  { title: 'Vim 执行外部命令',  content: ':!ls -la %      # 对当前文件执行\n:r !date          # 插入命令输出\n:%!python -m json.tool  # JSON 格式化全文', tags: ['vim'], is_public: false },
  { title: 'Vim 自动格式化',    content: 'gg=G             # 全文缩进格式化\n=ap             # 格式化当前段落\n=i{             # 格式化花括号内', tags: ['vim'], is_public: false },
  { title: 'Vim 编码设置',      content: ':set fileencoding=utf-8\n:set fileformat=unix\n# 文件尾乱码: :e ++ff=dos', tags: ['vim'], is_public: false },
  { title: 'Vim 会话管理',      content: ':mksession! session.vim    # 保存会话\nvim -S session.vim            # 恢复会话', tags: ['vim'], is_public: false },
  { title: 'Vim 替换模式',      content: 'R               # 进入替换模式 (REPLACE)\ngR              # 虚拟替换模式', tags: ['vim'], is_public: false },
  { title: 'Vim 可视模式',      content: 'v               # 字符可视\nV               # 行可视\nCtrl+v          # 块可视 (列模式)\no               # 切换选区端点', tags: ['vim'], is_public: false },
  { title: 'Vim 列编辑',        content: 'Ctrl+v → 选列 → Shift+i → 输入 → Esc\n# 批量列插入', tags: ['vim'], is_public: false },
  { title: 'Vim 行号设置',      content: ':set number          # 显示行号\n:set relativenumber  # 相对行号\n:set nu!             # 切换', tags: ['vim'], is_public: false },
  { title: 'Vim 配色方案',      content: ':colorscheme desert\n:set background=dark\n# 查看可用: :colorscheme 然后 Tab', tags: ['vim'], is_public: false },
  { title: 'Vim 状态栏',        content: ':set laststatus=2   # 始终显示\n:set statusline=%f%m%r%h%w\\ [%Y]\\ [%l,%v]\\ [%p%%]', tags: ['vim'], is_public: false },
  { title: 'Vim 快速修复窗口',  content: ':copen             # 打开 quickfix 列表\n:cnext / :cprev    # 下/上一项', tags: ['vim'], is_public: false },
  { title: 'Vim Diff 模式',     content: 'vim -d file1 file2      # 启动 diff\n:diffthis / :diffoff    # 开启/关闭\n[c / ]c               # 上下差异', tags: ['vim'], is_public: false },
  { title: 'Vim 帮助系统',      content: ':help keyword       # 查看帮助\n:help i_CTRL-N       # 插入模式 Ctrl+N\nCtrl+]               # 跳转链接', tags: ['vim'], is_public: false },
  { title: 'Vim 撤销树',        content: ':earlier 5m      # 回到 5 分钟前\n:later 30s        # 前进 30 秒\n# g+/g- 按时间导航', tags: ['vim'], is_public: false },
  { title: 'Vim 括号匹配跳转',  content: '%                 # 在括号间跳转\n[( 跳转到上一个 (\n[{ 跳转到上一个 {', tags: ['vim'], is_public: false },
  { title: 'Vim .vimrc 基础配置', content: `syntax on\nset number\nset expandtab tabstop=2 shiftwidth=2\nset smartindent\nset hlsearch incsearch\nset ignorecase smartcase`, tags: ['vim'], is_public: false },
  { title: 'Vim 读取命令输出',  content: ':r !ls            # 在光标处插入 ls 输出\n:0r !date          # 在文件头部插入日期', tags: ['vim'], is_public: false },
  { title: 'Vim 选择模式',      content: 'gh               # 进入选择模式 (类似可视但键入即替换)\ngH               # 行选择模式', tags: ['vim'], is_public: false },

  // ==================== Python (35 条) ====================
  { title: 'Python 虚拟环境',    content: 'python -m venv .venv\nsource .venv/bin/activate   # Linux/macOS\n.venv\\Scripts\\activate      # Windows', tags: ['python'], is_public: false },
  { title: 'Python pip 管理',    content: 'pip install -r requirements.txt\npip freeze > requirements.txt\npip list --outdated          # 查看过期包', tags: ['python'], is_public: false },
  { title: 'Python f-string 格式化', content: 'name = "World"\nprint(f"Hello {name}!")    # Hello World!\nprint(f"{3.14159:.2f}")    # 3.14', tags: ['python'], is_public: false },
  { title: 'Python 列表推导式',  content: 'squares = [x**2 for x in range(10)]\nevens = [x for x in nums if x % 2 == 0]', tags: ['python'], is_public: false },
  { title: 'Python 装饰器',      content: 'def timer(func):\n    import time\n    def wrapper(*a, **kw):\n        t0 = time.time(); r = func(*a, **kw)\n        print(f"{func.__name__}: {time.time()-t0:.3f}s")\n        return r\n    return wrapper', tags: ['python'], is_public: false },
  { title: 'Python 生成器',      content: 'def fibonacci(n):\n    a, b = 0, 1\n    for _ in range(n):\n        yield a\n        a, b = b, a + b', tags: ['python'], is_public: false },
  { title: 'Python argparse CLI', content: 'import argparse\np = argparse.ArgumentParser()\np.add_argument("-n", "--name", required=True)\nargs = p.parse_args()\nprint(args.name)', tags: ['python'], is_public: false },
  { title: 'Python async/await',  content: 'import asyncio\nasync def fetch(url):\n    async with aiohttp.ClientSession() as s:\n        async with s.get(url) as r:\n            return await r.json()', tags: ['python'], is_public: false },
  { title: 'Python dataclass',    content: 'from dataclasses import dataclass\n@dataclass\nclass Point:\n    x: float\n    y: float\n    def dist(self): return (self.x**2+self.y**2)**0.5', tags: ['python'], is_public: false },
  { title: 'Python collections',  content: 'from collections import defaultdict, Counter, deque\nc = Counter(["a","b","a"]); # {\'a\':2, \'b\':1}\nd = deque(maxlen=5)         # 定长队列', tags: ['python'], is_public: false },
  { title: 'Python Type Hints',   content: 'def greet(name: str, age: int = 0) -> str:\n    return f"{name} is {age}"\nfrom typing import List, Dict, Optional, Union', tags: ['python'], is_public: false },
  { title: 'Python Context Manager', content: 'with open("file.txt") as f:\n    data = f.read()\n# 自定义: 实现 __enter__ / __exit__', tags: ['python'], is_public: false },
  { title: 'Python pathlib 路径', content: 'from pathlib import Path\np = Path.home() / "projects"\np.mkdir(parents=True, exist_ok=True)\nfor f in p.glob("*.py"): print(f.name)', tags: ['python'], is_public: false },
  { title: 'Python JSON 处理',    content: 'import json\ndata = json.loads(\'{"key":"value"}\')\njson.dumps(data, indent=2, ensure_ascii=False)', tags: ['python'], is_public: false },
  { title: 'Python CSV 处理',     content: 'import csv\nwith open("data.csv") as f:\n    reader = csv.DictReader(f)\n    for row in reader:\n        print(row["name"])', tags: ['python'], is_public: false },
  { title: 'Python Requests HTTP', content: 'import requests\nr = requests.get("https://api.example.com", headers={"Auth":"token"})\nprint(r.json(), r.status_code)', tags: ['python'], is_public: false },
  { title: 'Python logging 日志', content: 'import logging\nlogging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")\nlogging.info("Hello")', tags: ['python'], is_public: false },
  { title: 'Python 异常处理',    content: 'try:\n    result = 1 / 0\nexcept ZeroDivisionError as e:\n    print(f"Error: {e}")\nelse:\n    print("No error")\nfinally:\n    print("Always")', tags: ['python'], is_public: false },
  { title: 'Python enumerate/zip', content: 'for i, val in enumerate(["a","b","c"]): print(i, val)\nfor n, s in zip(names, scores): print(f"{n}:{s}")', tags: ['python'], is_public: false },
  { title: 'Python map/filter',   content: 'list(map(str.upper, ["a","b"]))     # ["A","B"]\nlist(filter(lambda x: x>0, [-1,0,2]))  # [2]', tags: ['python'], is_public: false },
  { title: 'Python itertools',    content: 'from itertools import product, combinations, chain\nproduct("AB","12")  # A1,A2,B1,B2\ncombinations([1,2,3],2)  # (1,2),(1,3),(2,3)', tags: ['python'], is_public: false },
  { title: 'Python functools',    content: 'from functools import lru_cache, reduce\n@lru_cache(maxsize=128)\ndef fib(n): return n if n<2 else fib(n-1)+fib(n-2)', tags: ['python'], is_public: false },
  { title: 'Python 正则 re',      content: 'import re\nre.findall(r\'\\d+\', "a1b2c3")   # ["1","2","3"]\nre.sub(r\'\\s+\', \'_\', "hello world")  # hello_world', tags: ['python'], is_public: false },
  { title: 'Python datetime',     content: 'from datetime import datetime, timedelta\nnow = datetime.now()\ntomorrow = now + timedelta(days=1)\nnow.strftime("%Y-%m-%d %H:%M:%S")', tags: ['python'], is_public: false },
  { title: 'Python subprocess',   content: 'import subprocess\nresult = subprocess.run(["ls","-la"], capture_output=True, text=True)\nprint(result.stdout)', tags: ['python'], is_public: false },
  { title: 'Python threading',    content: 'from threading import Thread\ndef worker(n): print(f"Thread {n}")\nt = Thread(target=worker, args=(1,))\nt.start(); t.join()', tags: ['python'], is_public: false },
  { title: 'Python multiprocessing', content: 'from multiprocessing import Pool\nwith Pool(4) as p:\n    results = p.map(worker, range(10))', tags: ['python'], is_public: false },
  { title: 'Python unittest',     content: 'import unittest\nclass TestMath(unittest.TestCase):\n    def test_add(self):\n        self.assertEqual(1+1, 2)\nif __name__ == "__main__": unittest.main()', tags: ['python'], is_public: false },
  { title: 'Python pytest 简明',  content: '# pip install pytest\ndef test_addition():\n    assert 1 + 1 == 2\n# 运行: pytest -v --tb=short', tags: ['python'], is_public: false },
  { title: 'Python 字符串方法',   content: '"hello".upper()        # HELLO\n"  hi  ".strip()       # hi\n"a,b,c".split(",")     # [a,b,c]\n"-".join(["a","b"])    # a-b', tags: ['python'], is_public: false },
  { title: 'Python lambda 匿名函数', content: 'add = lambda a, b: a + b\nsorted(items, key=lambda x: x["age"])\nmap(lambda x: x*2, [1,2,3])', tags: ['python'], is_public: false },
  { title: 'Python walrus 海象运算符', content: '# Python 3.8+\nif (n := len(data)) > 10:\n    print(f"Data too long: {n} items")', tags: ['python'], is_public: false },
  { title: 'Python match/case',   content: '# Python 3.10+\nmatch status:\n    case 200: return "OK"\n    case 404: return "Not Found"\n    case _:   return "Unknown"', tags: ['python'], is_public: false },
  { title: 'Python Poetry 包管理', content: 'poetry new myproject\npoetry add requests\npoetry run python main.py\npoetry build', tags: ['python'], is_public: false },
  { title: 'Python 常用内置函数', content: '# any/all\ndir(list)     # 列出方法\nisinstance(42, int)  # True\nhasattr(obj, "attr")', tags: ['python'], is_public: false },

  // ==================== 其他 (35 条) ====================
  { title: 'curl API 调试',      content: 'curl -X POST https://api.example.com/data \\\n  -H "Content-Type: application/json" \\\n  -d \'{"key": "value"}\' \\\n  -v', tags: ['其他'], is_public: false },
  { title: 'jq JSON 处理',      content: 'cat data.json | jq \'.items[] | {name, price}\'\njq \'.[] | select(.status=="active")\'\njq \'group_by(.type) | map({type:.[0].type,count:length})\'', tags: ['其他'], is_public: false },
  { title: 'tmux 终端复用',     content: 'tmux new -s mysession       # 新建会话\ntmux attach -t mysession     # 重新接入\nCtrl+b % → 左右分屏   Ctrl+b " → 上下分屏', tags: ['其他'], is_public: false },
  { title: 'netstat/ss 网络检查', content: 'ss -tlnp                      # 监听端口\nss -s                         # 统计\nnetstat -i                    # 网卡流量', tags: ['其他'], is_public: false },
  { title: 'tcpdump 抓包',      content: 'tcpdump -i eth0 port 80 -w capture.pcap\ntcpdump -r capture.pcap -A\ntcpdump -i any \'host 10.0.0.1 and (port 80 or port 443)\'', tags: ['其他'], is_public: false },
  { title: 'ffmpeg 视频处理',   content: 'ffmpeg -i input.mp4 -c:v libx264 -crf 23 output.mp4\n# 截取: -ss 00:01:00 -t 30\n# 转 GIF: -vf "fps=10,scale=480:-1" output.gif', tags: ['其他'], is_public: false },
  { title: 'nc (netcat) 端口测试', content: 'nc -zv host 22                 # 端口连通性\nnc -l -p 8080                 # 临时监听\nnc host 8080 < file           # 文件传输', tags: ['其他'], is_public: false },
  { title: 'NGINX 反向代理配置', content: `server {\n  listen 80;\n  server_name example.com;\n  location / {\n    proxy_pass http://localhost:3000;\n    proxy_set_header Host $host;\n    proxy_set_header X-Real-IP $remote_addr;\n  }\n}`, tags: ['其他'], is_public: false },
  { title: 'systemd timer 替代 cron', content: `[Timer]\nOnCalendar=*-*-* 03:00:00\nPersistent=true\n[Install]\nWantedBy=timers.target`, tags: ['其他'], is_public: false },
  { title: '常用环境变量设置',    content: 'export PATH="$HOME/bin:$PATH"\nexport EDITOR=vim\nexport LANG=en_US.UTF-8\n# 写入 ~/.bashrc 或 ~/.zshrc 永久生效', tags: ['其他'], is_public: false },
  { title: 'ab 压力测试',       content: 'ab -n 10000 -c 100 https://example.com/\n# -n 请求总数 -c 并发数', tags: ['其他'], is_public: false },
  { title: 'wrk 高性能压测',    content: 'wrk -t4 -c100 -d30s https://example.com/api\n# -t 线程 -c 连接 -d 持续时间', tags: ['其他'], is_public: false },
  { title: 'iostat 磁盘 IO',    content: 'iostat -x 2 5                  # 每 2 秒, 共 5 次\niostat -p sda                  # 指定磁盘', tags: ['其他'], is_public: false },
  { title: 'vmstat 虚拟内存',   content: 'vmstat 2 5                    # 每 2 秒采集 5 次\nvmstat -s                      # 汇总统计', tags: ['其他'], is_public: false },
  { title: 'kill 信号大全',     content: 'kill -l                       # 列出所有信号\nkill -9 PID                    # 强制终止\nkill -15 PID                   # 优雅终止 (SIGTERM)', tags: ['其他'], is_public: false },
  { title: 'nice/renice 进程优先级', content: 'nice -n 10 ./cpu_task       # 低优先级启动\nrenice -n -5 -p PID           # 调高已有进程优先级', tags: ['其他'], is_public: false },
  { title: 'openssl 证书操作',  content: 'openssl x509 -in cert.pem -text -noout\nopenssl s_client -connect host:443 -servername host', tags: ['其他'], is_public: false },
  { title: 'base64 编解码',    content: 'echo -n "hello" | base64         # aGVsbG8=\necho "aGVsbG8=" | base64 -d   # hello', tags: ['其他'], is_public: false },
  { title: 'md5/sha256 哈希',  content: 'md5sum file.txt\nsha256sum file.txt\n# macOS: md5 file | shasum -a 256', tags: ['其他'], is_public: false },
  { title: 'gzip/bzip2 压缩',  content: 'gzip file.txt                  # .gz\ngzip -d file.txt.gz\ngunzip file.txt.gz', tags: ['其他'], is_public: false },
  { title: 'dd 磁盘操作',      content: 'dd if=/dev/sda of=disk.img bs=4M status=progress\n# 生成测试文件: dd if=/dev/zero of=test.bin bs=1M count=100', tags: ['其他'], is_public: false },
  { title: 'wget 下载工具',    content: 'wget -c https://example.com/file.zip    # 断点续传\nwget -r -l 2 -np -k https://example.com   # 递归下载', tags: ['其他'], is_public: false },
  { title: '批量重命名文件',   content: "# 将 .jpeg 改为 .jpg\nfor f in *.jpeg; do mv \"$f\" \"${f%.jpeg}.jpg\"; done\n# rename 命令: rename 's/\\.jpeg$/.jpg/' *.jpeg", tags: ['其他'], is_public: false },
  { title: 'sed 常用技巧',     content: "sed -n '5,10p' file            # 打印 5-10 行\nsed '/pattern/d' file           # 删除匹配行\nsed -i.bak 's/foo/bar/g' file   # 替换并备份", tags: ['其他'], is_public: false },
  { title: 'tr 字符转换',      content: "echo 'hello' | tr '[:lower:]' '[:upper:]'   # HELLO\necho 'a b c' | tr ' ' ','             # a,b,c\ntr -d '\\r' < dos.txt > unix.txt       # 删除回车符", tags: ['其他'], is_public: false },
  { title: 'cut 列提取',       content: "cut -d',' -f1,3 data.csv       # 按逗号分列取 1,3\ncut -c1-10 file.txt              # 每行前 10 字符", tags: ['其他'], is_public: false },
  { title: 'tee 分流输出',     content: './script.sh | tee output.log   # 输出到终端+文件\n./script.sh 2>&1 | tee -a log.txt  # 追加, 含 stderr', tags: ['其他'], is_public: false },
  { title: 'hexdump 十六进制', content: 'hexdump -C file.bin | head\nxxd file.bin                  # 更友好的显示', tags: ['其他'], is_public: false },
  { title: 'diff 文件对比',    content: 'diff -u old.txt new.txt          # 统一格式\ndiff -r dir1/ dir2/             # 递归对比目录\ncolordiff  # 彩色输出', tags: ['其他'], is_public: false },
  { title: 'which/whereis',    content: 'which python3                  # 显示命令路径\nwhereis python                 # 显示二进制+源码+手册', tags: ['其他'], is_public: false },
  { title: 'NGINX HTTPS 配置', content: `server {\n  listen 443 ssl http2;\n  ssl_certificate /etc/ssl/cert.pem;\n  ssl_certificate_key /etc/ssl/key.pem;\n  ssl_protocols TLSv1.2 TLSv1.3;\n}`, tags: ['其他'], is_public: false },
  { title: 'rsync 备份脚本',   content: `#!/bin/bash\nrsync -avz --delete /source/ user@host:/backup/$(date +%Y%m%d)/\n# 保留最近 7 天`, tags: ['其他'], is_public: false },
  { title: 'sshfs 远程挂载',   content: 'sshfs user@host:/remote/path /local/mount\n# 卸载: fusermount -u /local/mount', tags: ['其他'], is_public: false },
  { title: 'lsof 文件占用排查', content: 'lsof /var/log/syslog            # 谁在用这个文件\nlsof -u username                # 某用户的打开文件', tags: ['其他'], is_public: false },
  { title: 'Ansible ad-hoc',   content: 'ansible all -m ping -i inventory\nansible webservers -m shell -a "uptime" -i hosts', tags: ['其他'], is_public: false },
]

/** 按标签统计 */
export function getSeedCountByTag(): Record<string, number> {
  const count: Record<string, number> = {}
  SEED_COMMANDS.forEach((cmd) => {
    cmd.tags.forEach((tag) => {
      count[tag] = (count[tag] || 0) + 1
    })
  })
  return count
}

/** 获取所有种子命令的标签 */
export const SEED_TAGS = ['ssh', 'docker', 'linux', 'git', 'vim', 'python', '其他'] as const

/** 按标签获取种子命令 */
export function getSeedCommandsByTag(tag: string): SeedCommand[] {
  return SEED_COMMANDS.filter((cmd) => cmd.tags.includes(tag))
}
